stages:
  - build 
  # - deploy

variables:
  GIT_USER_NAME: root
  GIT_OPS_REPO_PWD: Osckorea1!
  GIT_OPS_REPO: gitlab.rocatdog.com:9443/root
  OPS_PROJECT: gitops
  DEPLOY_TYPE: web-app-test
  HARBOR_URL: harbor.rocatdog.com
  APP_IMG: web-app/test

init-build:  
  stage: build
  script:
    # 시작
    - echo "Building application..."
    - gradle --version
    - gradle build
    - echo "Gradle build Succeeded."
    - docker --version
    - docker login $HARBOR_URL -u admin -p $GIT_OPS_REPO_PWD
    - docker build -t $HARBOR_URL/$APP_IMG .
    - docker images | grep harbor
    - docker tag $HARBOR_URL/$APP_IMG $HARBOR_URL/$APP_IMG:v0.1
    - docker images | grep harbor
    - docker push $HARBOR_URL/$APP_IMG:v0.1
    - docker rmi $HARBOR_URL/$APP_IMG:v0.1
    - docker images | grep harbor
    - kustomize version 
    - echo "Build Succeeded..."
  tags:
    - kmpsss

deploy-job:      # This job runs in the deploy stage.
  stage: deploy
  script:
    - echo "Deploying application..."
    - pwd
    - ls -al
    # Git
    - git config --global user.name "root"
    - git config --global user.email "root@demo.com"
    - echo "https://$GIT_USER_NAME:$GIT_OPS_REPO_PWD@$GIT_OPS_REPO/$OPS_PROJECT.git"
    - git clone --single-branch --branch main "https://$GIT_USER_NAME:$GIT_OPS_REPO_PWD@$GIT_OPS_REPO/$OPS_PROJECT.git"
    - cd "$OPS_PROJECT/$DEPLOY_TYPE"
    - kustomize edit set image $HARBOR_URL/$APP_IMG:v0.1
# ff
    - git commit -am "Update image tag" && git push origin main
    - echo "Application successfully deployed."
  tags : 
    - kmpsss

